version: "3.4"

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    command: --authentication_policy=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: vish9812/my-comments-backend:1.3
    container_name: backend
    depends_on:
      - mysqldb
    build:
      context: src/server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      port: 5001
      db_host: mysqldb
      db_password: admin
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    labels:
      - appVersion=v1.3

  client:
    image: vish9812/my-comments-ui:1.3
    container_name: client
    depends_on:
      - backend
    build:
      context: src/client
      dockerfile: ./Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    labels:
      - appVersion=v1.3

  nginx:
    image: vish9812/my-comments-server:1.3
    depends_on:
      - client
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: nginx
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    labels:
      - appVersion=v1.3

  # portainer:
  #   image: portainer/portainer-ce
  #   container_name: portainer
  #   restart: always
  #   depends_on:
  #     - nginx
  #   ports:
  #     - "9443:9443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

volumes:
  mysql_data:
  # portainer_data:
